language: cpp

matrix:
 include:
  - os: linux
    dist: trusty
    addons:
      apt:
        sources:
          - sourceline: "ppa:beineri/opt-qt487-trusty"
        packages:
          - opt-qt4-qmake opt-qt4-dev-tools opt-libqt4-dev opt-libqt4-dev-bin opt-libqt4-opengl-dev
    sudo: required
    compiler: gcc
    env:
- QT_BASE=48
  - os: linux
    dist: trusty
    addons:
      apt:
        sources:
          - sourceline: "ppa:beineri/opt-qt-5.10.1-trusty"
        packages:
          - qt510base
    sudo: required
    compiler: gcc
    env:
- QT_BASE=510

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      source /opt/qt*/bin/qt*-env.sh
      qmake PREFIX=/usr -v
      qmake PREFIX=/usr -r
      make -j$(nproc); export COMPILE_RESULT=$?
      if [[ "$QT_BASE" != "510" ]]; then exit $COMPILE_RESULT; fi
      make install INSTALL_ROOT=AppDir
      wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
      chmod a+x linuxdeployqt*.AppImage 
      unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
      export VERSION=$(git rev-parse --short HEAD)
      ./linuxdeployqt*.AppImage ./AppDir/usr/share/applications/*.desktop -bundle-non-qt-libs
      ./linuxdeployqt*.AppImage --appimage-extract
      export PATH=$(readlink -f ./squashfs-root/usr/bin/):$PATH
      ./squashfs-root/usr/bin/appimagetool AppDir/
      mv ./Astree-$VERSION-x86_64.AppImage ./Astree-Linux-$VERSION-x86_64.AppImage
    fi

after_success:
  - |
    export GREP_PATH=grep;
    curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/Symbian9/Astree/commits/appimage -o repo.txt;
    export REMOTE=$($GREP_PATH -Po '(?<=: \")(([a-z0-9])\w+)(?=\")' -m 1 repo.txt);
    export LOCAL=$(git rev-parse HEAD);
    if [[ "$REMOTE" != "$LOCAL" ]]; then echo "Build no longer current. $REMOTE vs $LOCAL - aborting upload."; exit 0; fi;
    if [[ "$QT_BASE" = "510" && "$TRAVIS_OS_NAME" = "linux" ]]; then
      wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
      bash upload.sh LeoCAD*.AppImage*
    fi

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
- /^(?i:continuous)/
