language: cpp
compiler: gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-9
sudo: require
dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y
  - sudo apt-get update -qq
  

install:
  - sudo apt-get -y install qt59base libgl1-mesa-dev
  - source /opt/qt*/bin/qt*-env.sh

script:
  - cd src/gui
  - qmake CONFIG+=release PREFIX=/usr
  - make -j$(nproc)
  - cd ../..
  - mkdir astree
  - mkdir astree/usr
  - mkdir astree/usr/share
  - mkdir astree/usr/share/applications
  - cp astree.desktop astree/usr/share/applications/astree.desktop
  - make INSTALL_ROOT=astree -j$(nproc) install ; find astree/
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - ./linuxdeployqt-continuous-x86_64.AppImage astree/usr/share/applications/astree.desktop -appimage

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Astree*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
